name: camera_example
description: Demonstrates how to use the camera plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  camera:
    path: ../
  path_provider: ^1.6.18
  flutter:
    sdk: flutter
  video_player: ^0.11.0
  e2e: "^0.2.0"
  file_picker: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
